
INCLUDE(FindPkgConfig)

IF(NOT PKG_CONFIG_FOUND)
    MESSAGE(STATUS "Cannot find PKG-CONFIG cmake extensions. Kafka requires it.")
    IF (RDKAFKA_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "RDKAFKA support not found.")
    ENDIF (RDKAFKA_FIND_REQUIRED)
ELSE(NOT PKG_CONFIG_FOUND)

    PKG_CHECK_MODULES(RDKAFKA REQUIRED rdkafka)
    #MESSAGE(STATUS "-> ${RDKAFKA_FOUND}")
    #MESSAGE(STATUS "-> ${RDKAFKA_INCLUDE_DIRS}")
    #MESSAGE(STATUS "-> ${RDKAFKA_LIBRARIES}")

    IF(NOT ${RDKAFKA_FOUND})
        IF (RDKAFKA_FIND_REQUIRED)
            MESSAGE(FATAL_ERROR "RDKAFKA support not found.")
        ELSE (RDKAFKA_FIND_REQUIRED)
            MESSAGE(STATUS "RDKAFKA support not found.")
        ENDIF (RDKAFKA_FIND_REQUIRED)
    ENDIF(NOT ${RDKAFKA_FOUND})

ENDIF(NOT PKG_CONFIG_FOUND)

